### ISSUE TITLE
Trouble compiling on Ubuntu with Ruby 2.6

### ISSUE THREAD

**Issue by Marin-MK** [Ancurio/mkxp#218]
I've been following a guide that was posted here (https://docs.google.com/document/d/1xBHq2qccczn1ZcG4uc3DDGHhK0YxfmxI9TNRqjBLzFw/edit) and everything's fine until I try to compile mkxp. I've followed the guide exactly with 2 exceptions: at the start, `libpng12-dev` I had to change to `libpng-dev`, and the more relevant change, I got Ruby 2.6 instead of the Ruby 2.2 used in the guide. It could of course be that it's changed so much between 4 minor versions that the guide is no longer applicable, but if it isn't I'd love to know how to fix that.

I built Ruby statically as the guide also did, and I changed MRIVERSION to 2.6 and added `/usr/local/lib/libruby-static.a` under `${PLATFORM_LIBRARIES}` in mkxp's CMakeLists.txt. Here's the log when trying to build it.

```
marin@MarinPC:~/source/mkxp$ mkdir build && cd build

marin@MarinPC:~/source/mkxp/build$ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'sigc++-2.0'
--   Found sigc++-2.0, version 2.10.0
-- Checking for module 'pixman-1'
--   Found pixman-1, version 0.34.0
-- Checking for module 'physfs>=2.1'
--   Found physfs, version 3.1.0
-- Checking for module 'vorbisfile'
--   Found vorbisfile, version 1.3.5
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.9
-- Checking for module 'SDL2_ttf'
--   Found SDL2_ttf, version 2.0.15
-- Checking for module 'SDL2_image'
--   Found SDL2_image, version 2.0.4
-- Checking for module 'SDL_sound'
--   Found SDL_sound, version 1.0.1
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Checking for module 'ruby-2.6'
--   Found ruby-2.6, version 2.6.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marin/source/mkxp/build

marin@MarinPC:~/source/mkxp/build$ make
[  1%] Generating XXD for assets/icon.png
[  2%] Generating XXD for shader/common.h
[  3%] Generating XXD for shader/transSimple.frag
[  4%] Generating XXD for shader/trans.frag
[  5%] Generating XXD for shader/hue.frag
[  6%] Generating XXD for shader/sprite.frag
[  7%] Generating XXD for shader/plane.frag
[  9%] Generating XXD for shader/gray.frag
[ 10%] Generating XXD for shader/bitmapBlit.frag
[ 11%] Generating XXD for shader/flatColor.frag
[ 12%] Generating XXD for shader/simple.frag
[ 13%] Generating XXD for shader/simpleColor.frag
[ 14%] Generating XXD for shader/simpleAlpha.frag
[ 15%] Generating XXD for shader/simpleAlphaUni.frag
[ 17%] Generating XXD for shader/flashMap.frag
[ 18%] Generating XXD for shader/minimal.vert
[ 19%] Generating XXD for shader/simple.vert
[ 20%] Generating XXD for shader/simpleColor.vert
[ 21%] Generating XXD for shader/sprite.vert
[ 22%] Generating XXD for shader/tilemap.vert
[ 23%] Generating XXD for shader/tilemapvx.vert
[ 25%] Generating XXD for shader/blur.frag
[ 26%] Generating XXD for shader/blurH.vert
[ 27%] Generating XXD for shader/blurV.vert
[ 28%] Generating XXD for shader/simpleMatrix.vert
[ 29%] Generating XXD for assets/liberation.ttf
Scanning dependencies of target mkxp
[ 30%] Building CXX object CMakeFiles/mkxp.dir/src/main.cpp.o
[ 31%] Building CXX object CMakeFiles/mkxp.dir/src/audio.cpp.o
[ 32%] Building CXX object CMakeFiles/mkxp.dir/src/bitmap.cpp.o
[ 34%] Building CXX object CMakeFiles/mkxp.dir/src/eventthread.cpp.o
[ 35%] Building CXX object CMakeFiles/mkxp.dir/src/filesystem.cpp.o
[ 36%] Building CXX object CMakeFiles/mkxp.dir/src/font.cpp.o
[ 37%] Building CXX object CMakeFiles/mkxp.dir/src/input.cpp.o
[ 38%] Building CXX object CMakeFiles/mkxp.dir/src/plane.cpp.o
[ 39%] Building CXX object CMakeFiles/mkxp.dir/src/scene.cpp.o
[ 40%] Building CXX object CMakeFiles/mkxp.dir/src/sprite.cpp.o
[ 42%] Building CXX object CMakeFiles/mkxp.dir/src/table.cpp.o
[ 43%] Building CXX object CMakeFiles/mkxp.dir/src/tilequad.cpp.o
[ 44%] Building CXX object CMakeFiles/mkxp.dir/src/viewport.cpp.o
[ 45%] Building CXX object CMakeFiles/mkxp.dir/src/window.cpp.o
[ 46%] Building CXX object CMakeFiles/mkxp.dir/src/texpool.cpp.o
[ 47%] Building CXX object CMakeFiles/mkxp.dir/src/shader.cpp.o
[ 48%] Building CXX object CMakeFiles/mkxp.dir/src/glstate.cpp.o
[ 50%] Building CXX object CMakeFiles/mkxp.dir/src/tilemap.cpp.o
[ 51%] Building CXX object CMakeFiles/mkxp.dir/src/autotiles.cpp.o
[ 52%] Building CXX object CMakeFiles/mkxp.dir/src/graphics.cpp.o
[ 53%] Building CXX object CMakeFiles/mkxp.dir/src/gl-debug.cpp.o
[ 54%] Building CXX object CMakeFiles/mkxp.dir/src/etc.cpp.o
[ 55%] Building CXX object CMakeFiles/mkxp.dir/src/config.cpp.o
[ 56%] Building CXX object CMakeFiles/mkxp.dir/src/settingsmenu.cpp.o
[ 57%] Building CXX object CMakeFiles/mkxp.dir/src/keybindings.cpp.o
[ 59%] Building CXX object CMakeFiles/mkxp.dir/src/tileatlas.cpp.o
[ 60%] Building CXX object CMakeFiles/mkxp.dir/src/sharedstate.cpp.o
[ 61%] Building CXX object CMakeFiles/mkxp.dir/src/gl-fun.cpp.o
[ 62%] Building CXX object CMakeFiles/mkxp.dir/src/gl-meta.cpp.o
[ 63%] Building CXX object CMakeFiles/mkxp.dir/src/vertex.cpp.o
[ 64%] Building CXX object CMakeFiles/mkxp.dir/src/soundemitter.cpp.o
[ 65%] Building CXX object CMakeFiles/mkxp.dir/src/sdlsoundsource.cpp.o
[ 67%] Building CXX object CMakeFiles/mkxp.dir/src/alstream.cpp.o
[ 68%] Building CXX object CMakeFiles/mkxp.dir/src/audiostream.cpp.o
[ 69%] Building CXX object CMakeFiles/mkxp.dir/src/rgssad.cpp.o
[ 70%] Building CXX object CMakeFiles/mkxp.dir/src/bundledfont.cpp.o
[ 71%] Building CXX object CMakeFiles/mkxp.dir/src/vorbissource.cpp.o
[ 72%] Building CXX object CMakeFiles/mkxp.dir/src/windowvx.cpp.o
[ 73%] Building CXX object CMakeFiles/mkxp.dir/src/tilemapvx.cpp.o
[ 75%] Building CXX object CMakeFiles/mkxp.dir/src/tileatlasvx.cpp.o
[ 76%] Building CXX object CMakeFiles/mkxp.dir/src/autotilesvx.cpp.o
[ 77%] Building CXX object CMakeFiles/mkxp.dir/src/midisource.cpp.o
[ 78%] Building CXX object CMakeFiles/mkxp.dir/src/fluid-fun.cpp.o
[ 79%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/binding-mri.cpp.o
[ 80%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/binding-util.cpp.o
[ 81%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/table-binding.cpp.o
[ 82%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/etc-binding.cpp.o
[ 84%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/bitmap-binding.cpp.o
[ 85%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/font-binding.cpp.o
[ 86%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/graphics-binding.cpp.o
[ 87%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/input-binding.cpp.o
[ 88%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/sprite-binding.cpp.o
[ 89%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/viewport-binding.cpp.o
[ 90%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/plane-binding.cpp.o
[ 92%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/window-binding.cpp.o
[ 93%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/tilemap-binding.cpp.o
[ 94%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/audio-binding.cpp.o
[ 95%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/module_rpg.cpp.o
[ 96%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/filesystem-binding.cpp.o
[ 97%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/windowvx-binding.cpp.o
[ 98%] Building CXX object CMakeFiles/mkxp.dir/binding-mri/tilemapvx-binding.cpp.o
[100%] Linking CXX executable mkxp.bin.x86_64
/usr/bin/ld: /usr/local/lib/libruby-static.a(mjit.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/mkxp.dir/build.make:1766: recipe for target 'mkxp.bin.x86_64' failed
make[2]: *** [mkxp.bin.x86_64] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mkxp.dir/all' failed
make[1]: *** [CMakeFiles/mkxp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by carstene1ns** [comment]
General question is why do you link ruby statically and not dynamically like the rest?
This way you either need to build ruby without `dlopen` capability, or add `-ldl` to the linker.

**Comment by Marin-MK** [comment]
I'm completely in the dark without a guide, and the guide author says he had trouble with doing it dynamically. Since I don't even know how that works, I'm just following the guide I linked.

Could you either tell me where I should add `-ldl` to the linker, or how to build Ruby dynamically? Thanks for you help.

**Comment by carstene1ns** [comment]
For a quick fix, you can add it like you added the static ruby library (just add another line with `-ldl` in `CMakeLists.txt` after it).
Also, can you upload your `CMakeCache.txt`? Just drag/drop it into the editor field here, it will be uploaded.

**Comment by Marin-MK** [comment]
[CMakeCache.txt](https://github.com/Ancurio/mkxp/files/2923643/CMakeCache.txt)

**Comment by Marin-MK** [comment]
I'm now getting a different error:
```
/usr/bin/ld: /usr/local/lib/libruby-static.a(thread.o): undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/mkxp.dir/build.make:1766: recipe for target 'mkxp.bin.x86_64' failed
make[2]: *** [mkxp.bin.x86_64] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mkxp.dir/all' failed
make[1]: *** [CMakeFiles/mkxp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Ancurio** [comment]
Looks like the MRI pkg-config file needs to be updated with -ldl and
-lpthread?

2019年3月3日(日) 21:34 Marin <notifications@github.com>:

**Comment by carstene1ns** [comment]
Well this does only matter, because of manually adding the static library.
The pkg-config file has them included.

**Comment by Marin-MK** [comment]
Added `-lpthread` underneath `-ldl` and it raises yet another error.

```
/usr/bin/ld: /usr/local/lib/libruby-static.a(thread.o): undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
//lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/mkxp.dir/build.make:1766: recipe for target 'mkxp.bin.x86_64' failed
make[2]: *** [mkxp.bin.x86_64] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mkxp.dir/all' failed
make[1]: *** [CMakeFiles/mkxp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I clearly don't know what I'm doing anymore, so could someone explain how to dynamically link Ruby instead of statically? And then any differences with compiling mkxp with ruby statically and dynamically. That'd be very much appreciated.

**Comment by Ancurio** [comment]
@Marin-MK The manpages tell me `timer_settime` requires `-lrt`. You could alternatively try using the dependency kit as described in the Readme, if you're just trying to hack on mkxp.

**Comment by TomTheDragon** [comment]
I basicly tried the same thing as @Marin-MK but i only could get it to work with Ruby v2.2.x - v2.5.x (i tried v2.1.x, v2.2.x, v2.3.x, v2.4.x, v2.5.x and v2.6.x)
But even then, i still encountered a strange problem, as you can see here --> https://github.com/Ancurio/mkxp/issues/217

**Comment by Marin-MK** [comment]
> @Marin-MK The manpages tell me `timer_settime` requires `-lrt`. You could alternatively try using the dependency kit as described in the Readme, if you're just trying to hack on mkxp.

My main goal is to slightly alter mkxp's source code. For that I wanted to use the hack at first, but I couldn't get it to work (error below). That's why I tried compiling it from source.
```
marin@MarinPC:~/Desktop/mkxp-depkit$ ./setup_depkit.sh
marin@MarinPC:~/Desktop/mkxp-depkit$ source ./buildenv.sh
marin@MarinPC:~/Desktop/mkxp-depkit$ mkdir build && cd build
marin@MarinPC:~/Desktop/mkxp-depkit/build$ cmake -DBOOST_INCLUDEDIR=$BOOST_I -DBOOST_LIBRARYDIR=$BOOST_L -DOPENAL_INCLUDE_DIR=$OPENAL_I -DOPENAL_LIBRARY=$OPENAL_L ..
CMake Error: The source directory "/home/marin/Desktop/mkxp-depkit" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```


As for the `-lrt`, after adding it to the other list of arguments at the bottom of CMakeLists, I'm getting yet another error:
```
/usr/local/lib/libruby-static.a(bignum.o): In function `bary_mul_gmp':
/home/marin/source/ruby-2.6.0/bignum.c:2289: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2290: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2291: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2292: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2294: undefined reference to `__gmpz_mul'
/home/marin/source/ruby-2.6.0/bignum.c:2300: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/bignum.c:2302: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2303: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2304: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2297: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2298: undefined reference to `__gmpz_mul'
/usr/local/lib/libruby-static.a(bignum.o): In function `bary_divmod_gmp':
/home/marin/source/ruby-2.6.0/bignum.c:2759: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2760: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2761: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2762: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2764: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2765: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2774: undefined reference to `__gmpz_fdiv_qr'
/home/marin/source/ruby-2.6.0/bignum.c:2777: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2778: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2781: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/bignum.c:2783: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2787: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/bignum.c:2789: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2764: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2765: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2768: undefined reference to `__gmpz_fdiv_q'
/home/marin/source/ruby-2.6.0/bignum.c:2777: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2778: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2781: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/bignum.c:2783: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2759: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2760: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2762: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:2764: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2765: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:2771: undefined reference to `__gmpz_fdiv_r'
/home/marin/source/ruby-2.6.0/bignum.c:2777: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2778: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:2783: undefined reference to `__gmpz_clear'
/usr/local/lib/libruby-static.a(bignum.o): In function `big2str_gmp':
/home/marin/source/ruby-2.6.0/bignum.c:5017: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:5018: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:5020: undefined reference to `__gmpz_sizeinbase'
/home/marin/source/ruby-2.6.0/bignum.c:5029: undefined reference to `__gmpz_get_str'
/home/marin/source/ruby-2.6.0/bignum.c:5030: undefined reference to `__gmpz_clear'
/usr/local/lib/libruby-static.a(bignum.o): In function `str2big_gmp':
/home/marin/source/ruby-2.6.0/bignum.c:3976: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:3977: undefined reference to `__gmpz_set_str'
/home/marin/source/ruby-2.6.0/bignum.c:3981: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/bignum.c:3983: undefined reference to `__gmpz_clear'
/usr/local/lib/libruby-static.a(bignum.o): In function `bary_powm_gmp':
/home/marin/source/ruby-2.6.0/bignum.c:6934: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:6935: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:6936: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:6937: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/bignum.c:6938: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:6939: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:6940: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/bignum.c:6941: undefined reference to `__gmpz_powm'
/home/marin/source/ruby-2.6.0/bignum.c:6942: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/bignum.c:6944: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:6945: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:6946: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/bignum.c:6947: undefined reference to `__gmpz_clear'
/usr/local/lib/libruby-static.a(bignum.o): In function `Init_Bignum':
/home/marin/source/ruby-2.6.0/bignum.c:7167: undefined reference to `__gmp_version'
/usr/local/lib/libruby-static.a(string.o): In function `rb_str_crypt':
/home/marin/source/ruby-2.6.0/string.c:9319: undefined reference to `crypt_r'
/usr/local/lib/libruby-static.a(rational.o): In function `rb_gcd_gmp':
/home/marin/source/ruby-2.6.0/rational.c:246: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/rational.c:247: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/rational.c:248: undefined reference to `__gmpz_init'
/home/marin/source/ruby-2.6.0/rational.c:249: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/rational.c:250: undefined reference to `__gmpz_import'
/home/marin/source/ruby-2.6.0/rational.c:252: undefined reference to `__gmpz_gcd'
/home/marin/source/ruby-2.6.0/rational.c:254: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/rational.c:255: undefined reference to `__gmpz_clear'
/home/marin/source/ruby-2.6.0/rational.c:257: undefined reference to `__gmpz_sizeinbase'
/home/marin/source/ruby-2.6.0/rational.c:259: undefined reference to `__gmpz_export'
/home/marin/source/ruby-2.6.0/rational.c:261: undefined reference to `__gmpz_clear'
collect2: error: ld returned 1 exit status
CMakeFiles/mkxp.dir/build.make:1766: recipe for target 'mkxp.bin.x86_64' failed
make[2]: *** [mkxp.bin.x86_64] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mkxp.dir/all' failed
make[1]: *** [CMakeFiles/mkxp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

If Ruby 2.5 works too according to @TomTheDragon though, I could use that as well. Maybe Ruby just isn't easily compatible with mkxp.

**Comment by Ancurio** [comment]
> Any idea how I can get rid of that?

No clue; seems like it's related to the executable bit. You can check with `ls -l` if it's properly set.

> My main goal is to slightly alter mkxp's source code.

That's precisely why I made the depkit for..

**Comment by Marin-MK** [comment]
Using `ls -l` returns:
`-rwxr-xr-x  1 marin marin 22788256  9 20:39 mkxp.x86_64`

The prebuilt mkxp.amd64 and mkxp.x86 both have `-rwxrwx---`.

Notable is also that the file type is "Unknown" as opposed to "Program", and that it doesn't have a thumbnail in the file explorer.

**Comment by sorlok** [comment]
I realize it's been forever, but thanks to @Marin-MK for tracking this down and debugging it. I've updated the guide with your notes.
