### PR TITLE
Add MRI 1.8 Support

### PR DESCRIPTION
**Pull request by Ghabry**
This allows compiling of rmxp against Ruby 1.8.7 (tested with p374).

To test that it works simply start a RPG Maker XP game. If you get "Win32Api not found" instead of "Syntax error" it works ;).

This is mostly implemented by providing wrapper functions and macros (mostly copy-pasted from ruby 2.4) in binding-util.h. 

Known issues:
 - Everything encoding related is no-op by now. Includes the UTF8-Marhsaller. Guess I need to use the iconv-module here. I know that ruby reworked the whole encoding code in Ruby 2 but my Ruby knowledge is almost zero so I'm a bit lost here :(
 - ruby_option (like ruby_sysinit) segfaults when called.
 - rb_check_typeddata not implemented
 - rb_typeddata_is_kind_of not implemented
 - rb_hash_lookup2 not implemented but this is only in a RGSS3 codepath, so not relevant
 - rb_str_catf not implemented (so no stacktrace printed in error case)
 - raiseDisposedAccess will never raise

That typed data stuff was a bit tricky to fake because Ruby 1.8 does not have this typed data struct. But is good enough to launch games. Though some sanity checks are missing (see issues above)

To The Moon (Windows version) with 2.4 MRI:
screenshot_20170512_023350

With 1.8 MRI:
screenshot_20170512_023314

With 1.8 MRI and some WinApi emulation (Mouse cursor is stuck):
screenshot_20170512_023212

### CODE REVIEW

**Comment by Ghabry** [comment]
Also fixed compile for MRI 1.9, but this crashes with
"[BUG] object allocation during garbage collection phase"
on startup >.>

File: binding-mri/filesystem-binding.cpp [hunk 1]
```diff
@@ -130,7 +132,6 @@ kernelLoadDataInt(const char *filename, bool rubyExc)
 	VALUE port = fileIntForPath(filename, rubyExc);
 
 	VALUE marsh = rb_const_get(rb_cObject, rb_intern("Marshal"));
-
```
Comment (Ancurio) [inline binding-mri/filesystem-binding.cpp]: random whitespace change?

File: binding-mri/binding-util.cpp [hunk 2]
```diff
@@ -319,3 +323,73 @@ rb_get_args(int argc, VALUE *argv, const char *format, ...)
...
+VALUE rb_enc_associate_index(VALUE, int) {
+	return Qnil;
+}
+
+int rb_utf8_encindex(void) {
+	return 0;
+}
+
+VALUE rb_hash_lookup2(VALUE, VALUE, VALUE) {
+	return Qnil;
```
Comment (Ancurio) [inline binding-mri/binding-util.cpp]: What is the equivalent 1.8 function for this?

File: binding-mri/binding-util.cpp [hunk 3]
```diff
@@ -392,4 +392,5 @@ int rb_utf8_encindex(void) {
 VALUE rb_hash_lookup2(VALUE, VALUE, VALUE) {
 	return Qnil;
 }
-#endif
+#endif // RUBY_API_VERSION_MINOR == 8
+#endif // RUBY_API_VERSION_MAJOR == 1
```
Comment (Ancurio) [inline binding-mri/binding-util.cpp]: missing newline at end

File: binding-mri/binding-mri.cpp [hunk 4]
```diff
@@ -32,7 +32,7 @@
 #include "boost-hash.h"
 
 #include <ruby.h>
-#if RUBY_API_VERSION_MAJOR > 1
+#ifndef RUBY_LEGACY_VERSION
```
Comment (Ancurio) [inline binding-mri/binding-mri.cpp]: If this defined by a ruby header, or do we define it?

File: binding-mri/binding-mri.cpp [hunk 5]
```diff
@@ -571,9 +573,15 @@ static void mriBindingExecute()
 	 * stdio streams on some platforms (eg. Windows) */
 	int argc = 0;
 	char **argv = 0;
-	ruby_sysinit(&argc, &argv);
 
+#if RUBY_API_VERSION_MAJOR == 1
+	ruby_init();
+	//ruby_options(argc, argv);
```
Comment (Ghabry) [inline binding-mri/binding-mri.cpp]: Calling this somehow segfaults Ruby and I have no idea why. Will remove it.

File: binding-mri/binding-mri.cpp (hunk 4 above)
Comment (Ghabry) [inline binding-mri/binding-mri.cpp]: I define it. Problem is that checking for 1.8 vs. 1.9 is ugly to write so I introduced a new macro for 1.8 only. You can suggest a better macro name :D

**Comment by Ghabry** [comment]
> I can't comment too much on the 1.8 since I'm not familiar with the differences to 2.x
I'm also coding blind because the documentation for MRI 1.8 is basicly non-existent :D

Added raiseDisposedAccess (though the reported classname will be quite useless, just some internal class(#12345678). Though the bookkeeping for storing the "emulated typed data classname" somewhere is not worth the afford imho. So the sanity checks will also not work (they always return true)

rb_str_catf and rb_hash_lookup2 are implemented. hash_lookup is quite useless, only used in VX Ace codepath.

The stacktrace somehow only always contains one element in my tests and I have no idea why o.O

**Comment by Ghabry** [comment]
Rebased my changes but I can't test if I failed with my rebase because I can't get mkxp to compile because PhysFS changed the API >.>. I also applied @carstene1ns PR, but I still get

```
rgssad.cpp:507:1: error: conversión no válida de ‘int (*)(void*, const char*, PHYSFS_EnumerateCallback, const char*, void*) {aka int (*)(void*, const char*, PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*), const char*, void*)}’ a ‘PHYSFS_EnumerateCallbackResult (*)(void*, const char*, PHYSFS_EnumerateCallback, const char*, void*) {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*), const char*, void*)}’ [-fpermissive]
 };
 ^
rgssad.cpp:528:1: error: conversión no válida de ‘int (*)(void*, const char*, PHYSFS_EnumerateCallback, const char*, void*) {aka int (*)(void*, const char*, PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*), const char*, void*)}’ a ‘PHYSFS_EnumerateCallbackResult (*)(void*, const char*, PHYSFS_EnumerateCallback, const char*, void*) {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*), const char*, void*)}’ [-fpermissive]
 };
 ^
src/rgssad.cpp:638:1: error: conversión no válida de ‘int (*)(void*, const char*, PHYSFS_EnumerateCallback, const char*, void*) {aka int (*)(void*, const char*, PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*), const char*, void*)}’ a ‘PHYSFS_EnumerateCallbackResult (*)(void*, const char*, PHYSFS_EnumerateCallback, const char*, void*) {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*), const char*, void*)}’ [-fpermissive]
 };
 ^
make[2]: *** [CMakeFiles/mkxp.dir/build.make:983: CMakeFiles/mkxp.dir/src/rgssad.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
filesystem.cpp: En la función ‘int cacheEnumCB(void*, const char*, const char*)’:
filesystem.cpp:429:44: error: conversión no válida de ‘int (*)(void*, const char*, const char*)’ a ‘PHYSFS_EnumerateCallback {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*)}’ [-fpermissive]
   PHYSFS_enumerate(fullPath, cacheEnumCB, d);
                                            ^
In file included from src/rgssad.h:25:0,
                 from src/filesystem.cpp:24:
/usr/include/physfs.h:2746:17: nota:   argumento de inicialización 2 de ‘int PHYSFS_enumerate(const char*, PHYSFS_EnumerateCallback, void*)’
 PHYSFS_DECL int PHYSFS_enumerate(const char *dir, PHYSFS_EnumerateCallback c,
                 ^~~~~~~~~~~~~~~~
src/filesystem.cpp: En la función miembro ‘void FileSystem::createPathCache()’:
src/filesystem.cpp:452:41: error: conversión no válida de ‘int (*)(void*, const char*, const char*)’ a ‘PHYSFS_EnumerateCallback {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*)}’ [-fpermissive]
  PHYSFS_enumerate("", cacheEnumCB, &data);
                                         ^
In file included from src/rgssad.h:25:0,
                 from src/filesystem.cpp:24:
/usr/include/physfs.h:2746:17: nota:   argumento de inicialización 2 de ‘int PHYSFS_enumerate(const char*, PHYSFS_EnumerateCallback, void*)’
 PHYSFS_DECL int PHYSFS_enumerate(const char *dir, PHYSFS_EnumerateCallback c,
                 ^~~~~~~~~~~~~~~~
src/filesystem.cpp: En la función ‘int findFontsFolderCB(void*, const char*, const char*)’:
src/filesystem.cpp:517:46: error: conversión no válida de ‘int (*)(void*, const char*, const char*)’ a ‘PHYSFS_EnumerateCallback {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*)}’ [-fpermissive]
   PHYSFS_enumerate(fname, fontSetEnumCB, data);
                                              ^
In file included from src/rgssad.h:25:0,
                 from src/filesystem.cpp:24:
/usr/include/physfs.h:2746:17: nota:   argumento de inicialización 2 de ‘int PHYSFS_enumerate(const char*, PHYSFS_EnumerateCallback, void*)’
 PHYSFS_DECL int PHYSFS_enumerate(const char *dir, PHYSFS_EnumerateCallback c,
                 ^~~~~~~~~~~~~~~~
src/filesystem.cpp: En la función miembro ‘void FileSystem::initFontSets(SharedFontState&)’:
src/filesystem.cpp:526:45: error: conversión no válida de ‘int (*)(void*, const char*, const char*)’ a ‘PHYSFS_EnumerateCallback {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*)}’ [-fpermissive]
  PHYSFS_enumerate(".", findFontsFolderCB, &d);
                                             ^
In file included from src/rgssad.h:25:0,
                 from src/filesystem.cpp:24:
/usr/include/physfs.h:2746:17: nota:   argumento de inicialización 2 de ‘int PHYSFS_enumerate(const char*, PHYSFS_EnumerateCallback, void*)’
 PHYSFS_DECL int PHYSFS_enumerate(const char *dir, PHYSFS_EnumerateCallback c,
                 ^~~~~~~~~~~~~~~~
src/filesystem.cpp: En la función miembro ‘void FileSystem::openRead(FileSystem::OpenHandler&, const char*)’:
src/filesystem.cpp:663:46: error: conversión no válida de ‘int (*)(void*, const char*, const char*)’ a ‘PHYSFS_EnumerateCallback {aka PHYSFS_EnumerateCallbackResult (*)(void*, const char*, const char*)}’ [-fpermissive]
   PHYSFS_enumerate(dir, openReadEnumCB, &data);
                                              ^
In file included from src/rgssad.h:25:0,
                 from src/filesystem.cpp:24:
/usr/include/physfs.h:2746:17: nota:   argumento de inicialización 2 de ‘int PHYSFS_enumerate(const char*, PHYSFS_EnumerateCallback, void*)’
 PHYSFS_DECL int PHYSFS_enumerate(const char *dir, PHYSFS_EnumerateCallback c,
                 ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/mkxp.dir/build.make:263: CMakeFiles/mkxp.dir/src/filesystem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/mkxp.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Any idea?

**Comment by carstene1ns** [comment]
My PR is not yet updated with the change @Ancurio requested...
https://hg.icculus.org/icculus/physfs/rev/22c7dd45c588
https://hg.icculus.org/icculus/physfs/rev/97d3641bfba3

**Comment by Ghabry** [comment]
Thanks. https://gist.github.com/Ghabry/001c7e920b4a62089220866e7ce68a09  compiles for me now and can confirm that the rebase was successful 👍

**Comment by carstene1ns** [comment]
Thank you for fixing my PR! =)

**Comment by KuromeSan** [comment]
do you know if this works with ruby 1.8.1 specifically? iirc, the mkxp-z bindings dont

**Comment by Ghabry** [comment]
Not tested. Is there any game that does not work with 1.8.7?

**Comment by KuromeSan** [comment]
> Not tested. Because it is a minor update I assumed it does not have any breaking changes. Is there any game that does not work with 1.8.7?

yeah ive found one thats throwing some subclass error or some shit,

anyway tried on ruby 1.8.1, 
got 
```
root@Silica-Ubuntu:/home/silica/mkxp-ruby18/build# make
[  1%] Linking CXX executable mkxp.bin.x86_64
/usr/bin/ld: CMakeFiles/mkxp.dir/binding-mri/binding-util.cpp.o: in function `rb_hash_lookup2(unsigned long, unsigned long, unsigned long)':
binding-util.cpp:(.text+0x11ef): undefined reference to `rb_hash_lookup'

```

**Comment by Ghabry** [comment]
Is this the only error?

Replace the content of my rb_hash_lookup2 function with ``return def``

Should be fine because it is only used by rgss3 code

**Comment by KuromeSan** [comment]
maybe add like ifdef RUBY_API_VERSION_TEENY == 1  ?

**Comment by KuromeSan** [comment]
well it builds, but i get this when i try run even just a blank RTP game ..

**Comment by Ghabry** [comment]
Well no idea then.
Needs more work to find the underlying issue first
